source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraTableViewManager_Example' do
  pod "HaidoraTableViewManager", :path => "../"
end

target 'HaidoraTableViewManager_Tests' do
  pod "HaidoraTableViewManager", :path => "../"

  
end
