source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraTableViewManager_Example', :exclusive => true do
  pod "HaidoraTableViewManager", :path => "../"
end

target 'HaidoraTableViewManager_Tests', :exclusive => true do
  pod "HaidoraTableViewManager", :path => "../"

  
end
